<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lead Report - Table Only</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; margin: 0; padding: 20px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; margin: 0; }
        .header p { margin: 5px 0; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .won { background-color: #d4edda; color: #155724; }
        .lost { background-color: #f8d7da; color: #721c24; }
        .badge { display: inline-block; padding: 2px 5px; border-radius: 3px; font-size: 9px; margin-right: 2px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Shiva Polyfab - Lead Report</h1>
        <p>Generated on: {{ $filters['generated_at'] }} | Period: {{ $filters['from_date'] ?? 'All Time' }} {{ $filters['to_date'] ? 'to ' . $filters['to_date'] : '' }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Lead No</th>
                <th>Date</th>
                <th>Name</th>
                <th>Source</th>
                <th>Tags</th>
                <th>Response Time</th>
                <th>Lead Step</th>
                <th>Quotation</th>
                <th>Won/Lost</th>
            </tr>
        </thead>
        <tbody>
            @foreach($allResults as $lead)
            @php
                $statusSlug = $lead->status->slug ?? '';
                $rowClass = '';
                if ($statusSlug === 'won') $rowClass = 'won';
                elseif ($statusSlug === 'lost') $rowClass = 'lost';
                
                // Show 'Yes' if reached Quotation, Negotiation, or Won
                $hasQuotation = in_array($statusSlug, ['quotation', 'negotiation', 'won']);
            @endphp
            <tr class="{{ $rowClass }}">
                <td>{{ $lead->lead_no }}</td>
                <td>{{ $lead->created_at->format('d M, Y') }}</td>
                <td>{{ $lead->name }}</td>
                <td>{{ $lead->source->name ?? 'N/A' }}</td>
                <td>
                    @foreach($lead->tags as $tag)
                        <span class="badge" style="background: {{ $tag->color }}; color: #fff;">{{ $tag->name }}</span>
                    @endforeach
                </td>
                <td>-</td>
                <td>{{ $lead->status->name ?? 'N/A' }}</td>
                <td>{{ $hasQuotation ? 'Yes' : 'No' }}</td>
                <td>
                    @if($statusSlug === 'won') Won
                    @elseif($statusSlug === 'lost') Lost
                    @else Pending
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Page {PAGENO} of {TOTALPAGENO} | Generated by: {{ $filters['generated_by'] }}
    </div>
</body>
</html>
